version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: pioneer-pixel
    restart: always
    environment:
      POSTGRES_DB: pioneer-pixel
      POSTGRES_USER: pioneer-pixel
      POSTGRES_PASSWORD: 'test'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pioneer-pixel-network

  redis:
    image: redis:7
    container_name: pioneer-pixel-redis
    restart: always
    command: redis-server --requirepass test --bind 0.0.0.0 --save 60 1000 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pioneer-pixel-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - pioneer-pixel-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - pioneer-pixel-network

volumes:
  postgres_data:
  redis_data:

networks:
  pioneer-pixel-network:
    driver: bridge
